inpackage: true
with-expecter: true
filename: "mock_{{.InterfaceName}}_test.go"
packages:
  github.com/ruslantos/go-shortener-service/internal/handlers/getlink:
    config:
      dir: internal/handlers/getlink
    interfaces:
      linksService:
  github.com/ruslantos/go-shortener-service/internal/handlers/postlink:
    config:
      dir: internal/handlers/postlink
    interfaces:
      linksService:
  github.com/ruslantos/go-shortener-service/internal/handlers/shorten:
    config:
      dir: internal/handlers/shorten
    interfaces:
      linksService:
  github.com/ruslantos/go-shortener-service/internal/handlers/shortenbatch:
    config:
      dir: internal/handlers/shortenbatch
    interfaces:
      linksService: