// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shortenbatch

import (
	"context"

	"github.com/ruslantos/go-shortener-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// newMocklinksService creates a new instance of mocklinksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklinksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklinksService {
	mock := &mocklinksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklinksService is an autogenerated mock type for the linksService type
type mocklinksService struct {
	mock.Mock
}

type mocklinksService_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklinksService) EXPECT() *mocklinksService_Expecter {
	return &mocklinksService_Expecter{mock: &_m.Mock}
}

// AddBatch provides a mock function for the type mocklinksService
func (_mock *mocklinksService) AddBatch(ctx context.Context, links []models.Link) ([]models.Link, error) {
	ret := _mock.Called(ctx, links)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 []models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Link) ([]models.Link, error)); ok {
		return returnFunc(ctx, links)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Link) []models.Link); ok {
		r0 = returnFunc(ctx, links)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.Link) error); ok {
		r1 = returnFunc(ctx, links)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocklinksService_AddBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBatch'
type mocklinksService_AddBatch_Call struct {
	*mock.Call
}

// AddBatch is a helper method to define mock.On call
//   - ctx
//   - links
func (_e *mocklinksService_Expecter) AddBatch(ctx interface{}, links interface{}) *mocklinksService_AddBatch_Call {
	return &mocklinksService_AddBatch_Call{Call: _e.mock.On("AddBatch", ctx, links)}
}

func (_c *mocklinksService_AddBatch_Call) Run(run func(ctx context.Context, links []models.Link)) *mocklinksService_AddBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Link))
	})
	return _c
}

func (_c *mocklinksService_AddBatch_Call) Return(links1 []models.Link, err error) *mocklinksService_AddBatch_Call {
	_c.Call.Return(links1, err)
	return _c
}

func (_c *mocklinksService_AddBatch_Call) RunAndReturn(run func(ctx context.Context, links []models.Link) ([]models.Link, error)) *mocklinksService_AddBatch_Call {
	_c.Call.Return(run)
	return _c
}
