// Code generated by mockery v2.50.0. DO NOT EDIT.

package shortenbatch

import (
	models "github.com/ruslantos/go-shortener-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MocklinksService is an autogenerated mock type for the linksService type
type MocklinksService struct {
	mock.Mock
}

type MocklinksService_Expecter struct {
	mock *mock.Mock
}

func (_m *MocklinksService) EXPECT() *MocklinksService_Expecter {
	return &MocklinksService_Expecter{mock: &_m.Mock}
}

// AddBatch provides a mock function with given fields: links
func (_m *MocklinksService) AddBatch(links []models.Links) ([]models.Links, error) {
	ret := _m.Called(links)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 []models.Links
	var r1 error
	if rf, ok := ret.Get(0).(func([]models.Links) ([]models.Links, error)); ok {
		return rf(links)
	}
	if rf, ok := ret.Get(0).(func([]models.Links) []models.Links); ok {
		r0 = rf(links)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Links)
		}
	}

	if rf, ok := ret.Get(1).(func([]models.Links) error); ok {
		r1 = rf(links)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocklinksService_AddBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBatch'
type MocklinksService_AddBatch_Call struct {
	*mock.Call
}

// AddBatch is a helper method to define mock.On call
//   - links []models.Links
func (_e *MocklinksService_Expecter) AddBatch(links interface{}) *MocklinksService_AddBatch_Call {
	return &MocklinksService_AddBatch_Call{Call: _e.mock.On("AddBatch", links)}
}

func (_c *MocklinksService_AddBatch_Call) Run(run func(links []models.Links)) *MocklinksService_AddBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]models.Links))
	})
	return _c
}

func (_c *MocklinksService_AddBatch_Call) Return(_a0 []models.Links, _a1 error) *MocklinksService_AddBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocklinksService_AddBatch_Call) RunAndReturn(run func([]models.Links) ([]models.Links, error)) *MocklinksService_AddBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocklinksService creates a new instance of MocklinksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocklinksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocklinksService {
	mock := &MocklinksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
