// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package postlink

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMocklinksService creates a new instance of mocklinksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklinksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklinksService {
	mock := &mocklinksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklinksService is an autogenerated mock type for the linksService type
type mocklinksService struct {
	mock.Mock
}

type mocklinksService_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklinksService) EXPECT() *mocklinksService_Expecter {
	return &mocklinksService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type mocklinksService
func (_mock *mocklinksService) Add(ctx context.Context, long string) (string, error) {
	ret := _mock.Called(ctx, long)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, long)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, long)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, long)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocklinksService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mocklinksService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx
//   - long
func (_e *mocklinksService_Expecter) Add(ctx interface{}, long interface{}) *mocklinksService_Add_Call {
	return &mocklinksService_Add_Call{Call: _e.mock.On("Add", ctx, long)}
}

func (_c *mocklinksService_Add_Call) Run(run func(ctx context.Context, long string)) *mocklinksService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mocklinksService_Add_Call) Return(s string, err error) *mocklinksService_Add_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mocklinksService_Add_Call) RunAndReturn(run func(ctx context.Context, long string) (string, error)) *mocklinksService_Add_Call {
	_c.Call.Return(run)
	return _c
}
